version: "3.7"

services:
  mir2-backend:
    container_name: mir2-nani-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${USERPROFILE}\.mir2-nani:/

  mir2-admin:
    build:
      context: .
      dockerfile: src/Server/Server.Admin/Dockerfile
    container_name: mir2-nani-explorer
    ports: 
      - 80:80
    depends_on:
      - mir2-backend
