version: "3.7"

services:
  mir2-backend:
    container_name: mir2-backend
    image: mikepattyn/mir2-backend:latest
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mir2-admin:
    container_name: mir2-explorer
    image: mikepattyn/mir2-explorer:latest
    ports: 
      - 80:80
    depends_on:
      - mir2-backend
