name: Report
on:
  status:
    branches: [ main ]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: 'Notify'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: ${{ github.event }
